<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>VRPerfProfiler.LhmBridge</AssemblyName>
    <RootNamespace>VRPerfProfiler.LhmBridge</RootNamespace>
    <NuGetAudit>false</NuGetAudit>
    <NoWarn>$(NoWarn);NU1900</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
  </ItemGroup>
</Project>
